# Generated by Django 4.0.1 on 2022-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChirpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='font',
            field=models.CharField(choices=[('bold', 'Bold'), ('old', 'Old'), ('wild', 'Wild')], max_length=4),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
